# Generated by Django 4.2.6 on 2023-10-28 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OSMSector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A descriptive name for this sector.', max_length=255)),
                ('date_time', models.DateTimeField(auto_now_add=True, help_text='The date and time this sector was defined.')),
                ('bbox_upper_left_x', models.FloatField(help_text='Bounding box upper left corner, X-coordinate (longitude).')),
                ('bbox_upper_left_y', models.FloatField(help_text='Bounding box upper left corner, Y-coordinate (latitude).')),
                ('bbox_lower_right_x', models.FloatField(help_text='Bounding box lower right corner, X-coordinate (longitude).')),
                ('bbox_lower_right_y', models.FloatField(help_text='Bounding box lower right corner, Y-coordinate (latitude).')),
            ],
            options={
                'verbose_name': 'OSM Sector',
                'verbose_name_plural': 'OSM Sectors',
            },
        ),
    ]
