# Generated by Django 4.2.6 on 2023-10-28 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osmclient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osmsector',
            name='bbox_lower_right_x',
            field=models.FloatField(help_text='Bounding box right side (longitude).'),
        ),
        migrations.AlterField(
            model_name='osmsector',
            name='bbox_lower_right_y',
            field=models.FloatField(help_text='Bounding box upper side (latitude).'),
        ),
        migrations.AlterField(
            model_name='osmsector',
            name='bbox_upper_left_x',
            field=models.FloatField(help_text='Bounding box left side (longitude).'),
        ),
        migrations.AlterField(
            model_name='osmsector',
            name='bbox_upper_left_y',
            field=models.FloatField(help_text='Bounding box lower side (latitude).'),
        ),
    ]
